# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        python -m pip install -e .
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest .
    - name: Build documentation
      run: |
        # install sphinx and doctools
        sudo apt-get install -y pandoc
        pip install sphinx nbsphinx
        # run sphinx-build
        sphinx-build doc/source doc/build -b html
    - name: Publish documentation
      run: |
        cd doc/build
        git config --global user.email "nicobako@gmail.com"
        git config --global user.name "nicobako"
        git init
        git add .
        git commit -m "build html pages for gh-pages branch"
        git remote add origin https://nicobako:${{secrets.GITHUB_TOKEN}}@github.com/nicobako/kanbanflow.git
        git push --force origin master:gh-pages


